### ISSUE TITLE
Unable to install pyreduce using pip as well as github repo

### ISSUE THREAD

**Issue by Dishendramishra** [ivh/PyReduce#5]
OS: Manjaro Linux 19.0.2

## 1. Installing using github repo

```shell
➜  PyReduce git:(master) sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    from clib import build_extract
ImportError: cannot import name 'build_extract' from 'clib' (/usr/lib/python3.8/site-packages/clib/__init__.py)
```
then I checked for  **clib** module and I found that it is installed.

```shell
➜  PyReduce git:(master) pip3 show clib               
Name: clib
Version: 0.0.1
Summary: A command line base to help build CLIs faster.
Home-page: https://gitlab.com/iwaseatenbyagrue/clib
Author: eatenbyagrue
Author-email: iwaseatenbyagrue@gmail.com
License: UNKNOWN
Location: /usr/lib/python3.8/site-packages
Requires: click, click-plugins
Required-by: 
➜  PyReduce git:(master)
```

## 2. Installing using pip
```shell
➜  pipeline git:(master) sudo pip3 install pyreduce-astro
Collecting pyreduce-astro
  Using cached https://files.pythonhosted.org/packages/73/70/686f1b4da34302f64f2b7db62d9909b44dad9cec3a92f601b1c20e70ff57/pyreduce-astro-0.4.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hbfjqqxp/pyreduce-astro/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hbfjqqxp/pyreduce-astro/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-hbfjqqxp/pyreduce-astro/pip-egg-info
         cwd: /tmp/pip-install-hbfjqqxp/pyreduce-astro/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hbfjqqxp/pyreduce-astro/setup.py", line 15, in <module>
        from clib import build_extract
    ImportError: cannot import name 'build_extract' from 'clib' (/usr/lib/python3.8/site-packages/clib/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
➜  pipeline git:(master)
```

**Comment by Dishendramishra** [comment]
I found that if `clib` is already installed, `setup.py` ignores `clib` from current directory and imports it from the global lib location. You have a custom script called `build_extract.py`  in `clib` folder in current directory.

at present simple fix is before installing `pyreduce-astro` uninstall `clib`:

```shell
sudo pip3 uninstall clib
sudo pip3 install pyreduce-astro
```
